[package]
name = "loopy"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = "0.17.2"

[dev-dependencies]
criterion = "0.8.2"

[profile.dev]
opt-level = 0
debug = true
incremental = true
overflow-checks = true

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
debug = false

[[bench]]
name = "combine_bench"
path = "benches/combine_bench.rs"
harness = false

[[bench]]
name = "reduce_bench"
path = "benches/reduce_bench.rs"
harness = false

[[bench]]
name = "synchronous_bench"
path = "benches/synchronous_bench.rs"
harness = false
